# If you only want a lightweight installation of xiaozhi-server and only use the local configuration file, you don't need to worry about this file or modify anything in it.
# If you want to get the configuration from manager-api, please see below:
# Copy this file to the xiaozhi-server/data directory. If the data directory doesn't exist, create it and name the copied file .config.yaml.
# Note that if a .config.yaml file already exists in the data directory, please delete it first.
# First, start manager-api and manager-web, and register an account. The first account registered will be the administrator.
# As the administrator, go to the 【Parameter Management】 page, find 【server.secret】, and copy it to the parameter value. 
# Note that server.secret will change every time you deploy from scratch.
# Open the .config.yaml file in this data directory and modify manager-api.secret to the server.secret you just copied.
server:
  ip: 0.0.0.0
  port: 8000
  # http service port，for visual analysis interface
  http_port: 8003
  # Visual Analysis Interface Address
  # The interface address for sending visual analysis data to the device
  # If written using the default method below, the system will automatically generate a visual recognition address and output it in the startup log. You can directly access this address with a browser to confirm.
  # This address may not be accurate when deploying using Docker or a public network (using SSL, domain name).
  # Therefore, if you are deploying using Docker, set `vision_explain` to a local area network address.
  # If you are deploying using a public network, set `vision_explain` to a public network address.
  vision_explain: http://your_IP_address:port_number/mcp/vision/explain 
manager-api:
  # It's best to use a local area network IP address for your manager-api address.
  # If you are using Docker for deployment, please fill in the blank as follows: http://xiaozhi-esp32-server-web:8002/xiaozhi
  url: http://127.0.0.1:8002/xiaozhi
  # Your manager-api token is the server.secret you just copied.
  secret: 37953365-fe22-42be-8fef-e76838d20d33

# Default system prompt template file
prompt_template: agent-base-prompt.txt